[pushsecurity]
title = "pushsecurity"
url = "https://pushsecurity.com/blog"
entrySelector = ".blog-card"
titleSelector = ".blog-title"
linkSelector = ".site-blog-card-cmp a"
dateSelector = ".date"
dateFormat = "MMM dd, yyyy"

[axonius]
title = "axonius"
url = "https://axonius.com/blog"
entrySelector = ".grid__col--1-2-2-3-3-4 .Card-module-scss-module__QQputq__card"
titleSelector = ".Card-module-scss-module__QQputq__cardTitle"
linkSelector = ".Card-module-scss-module__QQputq__cardA"
dateSelector = ".Card-module-scss-module__QQputq__cardAuthorDate"
dateFormat = "MMM dd, yyyy"

[codeintegrity]
title = "codeintegrity"
url = "https://www.codeintegrity.ai/blog"
entrySelector = ".grid a"
titleSelector = ".grid .text-lg"
linkSelector = "*"
dateSelector = "time"
dateFormat = "MMM d, yyyy"

[ox-security]
title = "ox-security"
url = "https://www.ox.security/blog"
entrySelector = ".blog-post-container article"
titleSelector = ".entry-title"
linkSelector = ".blog-post-img-link"
dateSelector = ".post-date"
dateFormat = "MMMM d, yyyy"

[cyera]
title = "cyera"
url = "https://www.cyera.com/blog"
entrySelector = ".resource_item--blog"
titleSelector = ".resource-card__heading"
linkSelector = ".resource_item-link--blog"
dateSelector = ".resource-card__date"
dateFormat = "MMM d, yyyy"

[formal]
title = "formal"
url = "https://www.joinformal.com/blog/"
entrySelector = ".mt-10 a"
titleSelector = ".mt-2"
linkSelector = "*"

[raven]
title = "raven"
url = "https://raven.io/blog"
entrySelector = ".blog-card"
titleSelector = ".blog-card-content .lines-3-text"
linkSelector = ".learn-more-link"

[operant]
title = "operant"
url = "https://www.operant.ai/art-kubed"
entrySelector = ".blog-v1-grid .w-dyn-item"
titleSelector = ".blog-card-title"
linkSelector = ".blog-card-wrapper"

[cogent]
title = "cogent"
url = "https://www.cogent.security/resources"
entrySelector = ".ssr-variant > div > div > div:nth-child(3) a"
titleSelector = "> div:nth-child(2) > div:nth-child(2) > h4"
linkSelector = "*"
dateSelector = "> div:nth-child(2) > div:nth-child(1) > h4"
dateFormat = "MMM d, yyyy"

[maze]
title = "maze"
url = "https://mazehq.com/blog"
entrySelector = "#blog a"
titleSelector = ".c-tile-article__copy"
linkSelector = "*"
dateSelector = ".tag__date"
dateFormat = "MMMM d, yyyy"

[niteshsurana]
title = "niteshsurana"
url = "https://niteshsurana.com/"
entrySelector = "body > div:nth-child(6) > ul li"
titleSelector = "a"
linkSelector = "a"
dateSelector = "*"
dateFormat = "yyyy-MM-dd"

[chainguard]
title = "chainguard"
url = "https://www.chainguard.dev/unchained"
entrySelector = "main > section:nth-child(2) > ul > li"
titleSelector = ".card-text h3"
linkSelector = "a"
dateSelector = ".card-data time"
dateFormat = "MMMM d, yyyy"

[trustoncloud]
title = "trustoncloud"
url = "https://trustoncloud.com/blog"
entrySelector = "main > div > section:nth-child(3) article"
titleSelector = ".elementor-post__title"
linkSelector = "a.elementor-post__thumbnail__link"

[hush_security]
title = "hush_security"
url = "https://www.hush.security/blog"
entrySelector = ".blog_item"
titleSelector = ".heading-style-h6"
linkSelector = ".blog_item-link"
dateSelector = ".blog_author_text-wrapper > div:nth-child(2)"
dateFormat = "MMM d, yyyy"

[mnemonic]
title = "mnemonic"
url = "https://www.mnemonic.io/resources/blog/"
entrySelector = ".justify-content-center > div > ul > li"
titleSelector = ".partial-title--has-link a"
linkSelector = ".partial-title--has-link a"
dateSelector = ".partial__byline__date"
dateFormat = "dd.MM.yyyy"

[ryan_gerstenkorn]
title = "ryan_gerstenkorn"
url = "https://blog.ryanjarv.sh/"
entrySelector = ".posts li"
titleSelector = "a"
linkSelector = "a"
dateSelector = "span"
dateFormat = "dd MMM yyyy"

[pvotal]
title = "pvotal"
url = "https://pvotal.tech/blog/"
entrySelector = ".wpr-grid-item"
titleSelector = ".wpr-grid-item-title a"
linkSelector = ".wpr-grid-item-title a"
dateSelector = ".wpr-grid-item-date > div > span"
dateFormat = "MMMM d, yyyy"

[risk3sixty]
title = "risk3sixty"
url = "https://risk3sixty.com/blog"
entrySelector = "article.elementor-post"
titleSelector = ".elementor-post__title"
linkSelector = ".elementor-post__title a"

[kerbit]
title = "kerbit"
url = "https://kerbit.io/#research"
entrySelector = "#blogCardContainer .research-card"
titleSelector = ".research-card-title"
linkSelector = "a"

[zviwex]
title = "zviwex"
url = "https://zviwex.com/"
entrySelector = ".wrapper__main >div.post:nth-of-type(n+2)"
titleSelector = ".post__content a"
linkSelector = ".post__content a"
dateSelector = ".post__footer-date"
dateFormat = "dd MMM yyyy"

[ssd_disclosure]
title = "ssd_disclosure"
url = "https://ssd-disclosure.com/advisories/"
entrySelector = ".elementor-post__card"
titleSelector = ".elementor-post__title a"
linkSelector = ".elementor-post__title a"

[equixly]
title = "equixly"
url = "https://equixly.com/blog/"
entrySelector = ".blog ul li"
titleSelector = "h3"
linkSelector = "a"
dateSelector = "time"
dateFormat = "MM/dd/yy"

[mercari_security]
title = "mercari_security"
url = "https://engineering.mercari.com/en/blog/category/security/"
entrySelector = ".left > ul > li"
titleSelector = "h3"
linkSelector = "a"
dateSelector = "time"
dateFormat = "yyyy/MM/dd"

[security_googlecloudcommunity]
title = "security_googlecloudcommunity"
url = "https://security.googlecloudcommunity.com/p/blog"
entrySelector = ".topic-list-item-card"
titleSelector = ".topic-list-item-card_title-text"
linkSelector = ".topic-list-item-card_body"
dateSelector = "time"
dateFormat = "yyyy-MM-ddThh:mm:ss.SSSZ"

[beelzebub]
title = "beelzebub"
url = "https://beelzebub.ai/blog/"
entrySelector = ".grid article"
titleSelector = "h2"
linkSelector = "a.btn-text"
dateSelector = ".font-primary > span:nth-child(1)"
dateFormat = "MMM dd, yyyy"

[exaforce]
title = "exaforce"
url = "https://www.exaforce.com/blog"
entrySelector = ".blog_list-item"
titleSelector = "h2.heading_blog"
linkSelector = ".card_link"
dateSelector = "p.blog_description"
dateFormat = "MMM do, yyyy"

[buganizer]
title = "buganizer"
url = "https://buganizer.cc/"
entrySelector = "li"
titleSelector = "a"
linkSelector = "a"
dateSelector = "*"
dateFormat = "MMM yyyy"

[yoshino_s]
title = "yoshino_s"
url = "https://blog.yoshino-s.xyz/blog/"
entrySelector = "main article"
titleSelector = "header h2 > a"
linkSelector = "header h2 > a"
dateSelector = "header time"
dateFormat = "yyyy-MM-ddThh:mm:ss.SSSZ"

[skybound]
title = "skybound"
url = "https://www.skybound.link/"
entrySelector = ".posts article"
titleSelector = ".post-title a"
linkSelector = ".post-title a"
dateSelector = ".post-meta time"
dateFormat = "yyyy-MM-dd"

[flowerwitch]
title = "flowerwitch"
url = "https://flowerwitch.github.io/"
entrySelector = "#content-body article"
titleSelector = "a.article-title"
linkSelector = "a.article-title"
dateSelector = ".meta-info time"
dateFormat = "yyyy-MM-ddThh:mm:ss.SSSZ"

[trimarcsecurity]
title = "trimarcsecurity"
url = "https://www.trimarcsecurity.com/hub"
entrySelector = ".gallery-item-container"
titleSelector = ".post-title h2"
linkSelector = "a"
dateSelector = ".post-metadata__date"
dateFormat = "MMM d, yyyy"

[sweet_security]
title = "sweet_security"
url = "https://www.sweet.security/blog"
entrySelector = ".w-dyn-item"
titleSelector = ".blog-item-title-h4-regular"
linkSelector = "a"

[awssecuritydigest]
title = "awssecuritydigest"
url = "https://awssecuritydigest.com/articles"
entrySelector = ".card"
titleSelector = "h2 a"
linkSelector = "h2 a"
dateSelector = ".date"
dateFormat = "MMMM d, yyyy"

[armosec]
title = "armosec"
url = "https://www.armosec.io/blog/"
entrySelector = ".blog-articles__list .blog-article"
titleSelector = ".blog-article__title"
linkSelector = "*"
dateSelector = ".blog-article__meta li"
dateFormat = "MMM d, yyyy"

[halcyon_ai]
title = "halcyon_ai"
url = "https://www.halcyon.ai/blog"
entrySelector = ".cms-card-collection-item"
titleSelector = ".heading-style-cms-card"
linkSelector = ".cms-card_item"
dateSelector = ".text-style-date"
dateFormat = "MMM d, yyyy"

[sans_edu_cloud_sec]
title = "sans_edu_cloud_sec"
url = "https://www.sans.edu/cyber-research/?focus-area=cloud-security"
entrySelector = ".article-listing__item"
titleSelector = ".title"
linkSelector = ".block-link"
dateSelector = ".date"
dateFormat = "MMMM d, yyyy"
