[pushsecurity]
title = "pushsecurity"
url = "https://pushsecurity.com/blog"
entrySelector = ".blog-card"
titleSelector = ".blog-title"
linkSelector = ".site-blog-card-cmp a"

[axonius]
title = "axonius"
url = "https://axonius.com/blog"
entrySelector = ".grid__item"
titleSelector = ".text__title Card-module-scss-module__QQputq__cardTitle"
linkSelector = ".Card-module-scss-module__QQputq__cardA"
